import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {AppSidebar, SidebarProvider, SidebarInset} from "@/components/app-sidebar";
import {FlexBox} from "@/components/custom-ui/flex-box";
import {AppProviders} from "@/components/app-providers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased`}>
        <AppProviders>
            <SidebarProvider>
                <AppSidebar className="hidden md:flex"/>
                <FlexBox className="max-w-full min-w-0">
                    <SidebarInset className="w-full py-6 px-4 lg:p-6">
                        {children}
                    </SidebarInset>
                    <footer className="h-52 w-full "/>
                </FlexBox>
            </SidebarProvider>
        </AppProviders>
        </body>
        </html>
    );
}
